subscribers:
  - name:        "policy"
    topic:       "/policy/cmd_vel"
    timeout:     0.1
    priority:    1
    short_desc:  "Policy cmd_vels"
  - name:        "Nav Stack"
    topic:       "/nav/cmd_vel"
    timeout:     0.5
    priority:    10
    short_desc:  "Navigation stack controller"
  - name:        "Joy controller"
    topic:       "/joy/cmd_vel"
    timeout:     0.3
    priority:    0
publisher:       "/cmd_vel"